language: java
jdk:
- openjdk11
install: "/bin/true"
sudo: required
services:
- docker
script:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
- if [ ! -z "${TRAVIS_TAG}" ]; then mvn versions:set -DnewVersion=${TRAVIS_TAG:1}; fi
- mvn clean install -q
cache:
  directories:
  - "$HOME/.m2"
before_deploy:
  - export WEBGOAT_SERVER_TARGET_DIR=$HOME/build/$TRAVIS_REPO_SLUG/webgoat-server/target
  - export WEBWOLF_TARGET_DIR=$HOME/build/$TRAVIS_REPO_SLUG/webwolf/target
  - export WEBGOAT_ARTIFACTS_FOLDER=$HOME/build/$TRAVIS_REPO_SLUG/Deployable_Artifacts/
  - mkdir -p $WEBGOAT_ARTIFACTS_FOLDER
  - cp -fa $WEBGOAT_SERVER_TARGET_DIR/*.jar $WEBGOAT_ARTIFACTS_FOLDER/
  - cp -fa $WEBWOLF_TARGET_DIR/*.jar $WEBGOAT_ARTIFACTS_FOLDER/
  - echo "Contents of artifacts folder:"
  - ls $WEBGOAT_ARTIFACTS_FOLDER
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy-webgoat.sh
    on:
      repo: $DOCKER_USER/WebGoat
      tags: true
after_deploy:
  - docker pull $DOCKER_USER/webgoat:latest
  - docker run -p 8080:8080 $DOCKER_USER/webgoat:latest  &
  - docker ps -a
  - docker pull owasp/zap2docker-stable
  - docker run -t owasp/zap2docker-stable zap-baseline.py -t http://172.17.0.2:8080/WebGoat
  - docker ps -a
  - docker inspect 
        $(docker ps |grep $DOCKER_USER/webgoat 
        | awk '{print $1}')
        | grep IPAddress
  - docker kill 
        $(docker ps |grep $DOCKER_USER/webgoat 
        | awk '{print $1}')
